### ISSUE TITLE
VSCode extension cannot set up Python environment on Windows

### ISSUE THREAD

**Issue by senko** [Pythagora-io/gpt-pilot#387]
When setting up GPT-Pilot VSCode extension in windows, one of the steps is to create the Python virtual environment (venv).

This can fail (for as of yet unknown reason), and this is what the users see:

![image](https://github.com/Pythagora-io/gpt-pilot/assets/3362/7dbd5926-c94b-404c-b1eb-eaaef606c701)

Temporary workaround:

1.  open command line in the `gpt-pilot` sub-directory of the folder which you selected for the installation (Test in your video)
2.  create the virtual environment with `python -m venv pilot-env`
3.  activate the environment with `pilot-env\Scripts\activate`
4.  install packages with `pip install -r requirements.txt`
5. go to the `pilot` subdirectory (not `pilot-env`, just `pilot`), then run `python db_init.py` to initialize the database

After doing the above steps, the VSCode extension should start working.

**Comment by senko** [comment]
This is likely caused by the way we chain commands to go to the directory, create the env and set it up in the VSCode extension installer script.

**Comment by Eforen** [comment]
I am having the same error except when I try to do your workaround I get a long list of errors that flash on the screen and then disapear 
![image](https://github.com/Pythagora-io/gpt-pilot/assets/725683/79f269bd-7546-4496-8f30-e347d1549df5)

To me it looks like 
```
python db_init.py
```
Was unsuccessful. When I run the command should it have any output? (I have no output but also no errors)

**Comment by fahdmirza** [comment]
Hi,
 Issue still persists even after workaround. I did a video on it https://youtu.be/ZtOBOHf5lTs?si=VXP2hbYKGcuzJhlN

**Comment by jdavid82** [comment]
> When setting up GPT-Pilot VSCode extension in windows, one of the steps is to create the Python virtual environment (venv).
> 
> This can fail (for as of yet unknown reason), and this is what the users see:
> 
> ![image](https://private-user-images.githubusercontent.com/3362/292340111-7dbd5926-c94b-404c-b1eb-eaaef606c701.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjI2MjUsIm5iZiI6MTcwMzIyMjMyNSwicGF0aCI6Ii8zMzYyLzI5MjM0MDExMS03ZGJkNTkyNi1jOTRiLTQwNGMtYjFlYi1lYWFlZjYwNmM3MDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDUxODQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmY0MWZjNmI5NjcyYzJhY2IwOTQ5NjExNzE4ODE5NmE4MWY0NjczMWVhMzZkM2MxMDgzMWE1YzUyODYzODg4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wlBQvFkwK1BQWIMqvUkWVGSDV0bH3YZ43iXakDLOfhI)
> 
> Temporary workaround:
> 
>     1. open command line in the `gpt-pilot` sub-directory of the folder which you selected for the installation of GPT Pilot (there should be `requirements.txt` file already there)
> 
>     2. create the virtual environment with `python -m venv pilot-env`
> 
>     3. activate the environment with `pilot-env\Scripts\activate`
> 
>     4. install packages with `pip install -r requirements.txt`
> 
>     5. go to the `pilot` subdirectory (not `pilot-env`, just `pilot`), then run `python db_init.py` to initialize the database
> 
> 
> After doing the above steps, the VSCode extension should start working.

This worked for me

**Comment by senko** [comment]
We've just published an update to the VSCode extension (version 0.0.21) that fixes this.

After you install the update, you'll need to go to Settings (in the extension) and choose a different (new) directory for gpt-pilot installation. This is because the old folder has incomplete install, which gives that error. Alternatively you can just remove that gpt-pilot folder in the windows explorer and start the extension which will try to re-initialize it.

@Eforen @fahdmirza @jdavid82 please try it out and let us know if that fixes it for you.

**Comment by MikeTheBard** [comment]
Tried the update on Windows:

"Traceback (most recent call last):

File "d:\prog\gpt-pilot\workspace/gpt-pilot/pilot/main.py", line 8, in

from dotenv import load_dotenv

ModuleNotFoundError: No module named 'dotenv'"

**Comment by SerenityNrrd** [comment]
![image](https://github.com/Pythagora-io/gpt-pilot/assets/6841787/600e23f3-9402-4364-8a7f-d00dd259aefa)
I am still getting this error this morning.

**Comment by dreamrec** [comment]
> ![image](https://private-user-images.githubusercontent.com/6841787/292511015-600e23f3-9402-4364-8a7f-d00dd259aefa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNTgzNjAsIm5iZiI6MTcwMzI1ODA2MCwicGF0aCI6Ii82ODQxNzg3LzI5MjUxMTAxNS02MDBlMjNmMy05NDAyLTQzNjQtOGE3Zi1kMDBkZDI1OWFlZmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMTUxNDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTlhMjJlMzBiYWY5N2M3NzJlYzNmYzQ4OGVlODQyNzJkYWI3MGU5ZmNkZjYxMDVhMzc1MzMyNGE5MDhmODY5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sHtPzrsH0Q5zG5M3p5634D-Njbd-KTy-d7a0h9DUTlw) I am still getting this error this morning.

same

**Comment by brain1961** [comment]
Just adding this to see if it helps locate the cause of this issue.
After the install, I get this error:
Traceback (most recent call last):
File "c:\AI\gpt-pilot\workspace/gpt-pilot/pilot/main.py", line 8, in
from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

See image

I did try deleting the workspace directory and letting it re-initialize it. This caused an error because the last slash in the path was incorrect, (see image) which made it just loop. I manually created the directories and it did re-initialize the workspace, but didn't fix the above error.

Brian 

![New app error](https://github.com/Pythagora-io/gpt-pilot/assets/40923847/616b3df3-e490-4273-8c39-84f37f1ab2d6)
![workspace](https://github.com/Pythagora-io/gpt-pilot/assets/40923847/5288b53d-0d97-4bb4-908f-a533ad09dfc7)

**Comment by MikeTheBard** [comment]
> Just adding this to see if it helps locate the cause of this issue. After the install, I get this error: Traceback (most recent call last): File "c:\AI\gpt-pilot\workspace/gpt-pilot/pilot/main.py", line 8, in from dotenv import load_dotenv ModuleNotFoundError: No module named 'dotenv'
> 
> See image
> 
> I did try deleting the workspace directory and letting it re-initialize it. This caused an error because the last slash in the path was incorrect, (see image) which made it just loop. I manually created the directories and it did re-initialize the workspace, but didn't fix the above error.
> 
> Brian
> 
> ![New app error](https://private-user-images.githubusercontent.com/40923847/292536021-616b3df3-e490-4273-8c39-84f37f1ab2d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNzIxMzQsIm5iZiI6MTcwMzI3MTgzNCwicGF0aCI6Ii80MDkyMzg0Ny8yOTI1MzYwMjEtNjE2YjNkZjMtZTQ5MC00MjczLThjMzktODRmMzdmMWFiMmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDE5MDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ZWY2NzI0Yjg5MWNjOGI4YTY4NmEzOTc3NjcwNjM5ZDA0OTJlOWM4NjU3NTdmNDQxNzBkODZmNzQyZTU3YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jha2fSF-Y6RmLGoKLR6r1R8mruylnrEj7P8CBUCaJx8) ![workspace](https://private-user-images.githubusercontent.com/40923847/292536052-5288b53d-0d97-4bb4-908f-a533ad09dfc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNzIxMzQsIm5iZiI6MTcwMzI3MTgzNCwicGF0aCI6Ii80MDkyMzg0Ny8yOTI1MzYwNTItNTI4OGI1M2QtMGQ5Ny00YmI0LTkwOGYtYTUzM2FkMDlkZmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDE5MDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYzYxMTA4ZWQ0NTRiYmM3OTdmMzBhNDdiYTQ2ODYxOGE4M2YxOGM5NjViYjY5YjY2ZmRhMzU0MWVjZWY2ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AiWC1XmEv0Eq0iu_UMd36zJxeCAdqFKgz7mU5Ky-g8o)

Having this same issue on Windows.

**Comment by Eforen** [comment]
Didn't have to manaully go in and fix the install to get to the same point but still the same result.

**Comment by metathron** [comment]
> ![image](https://private-user-images.githubusercontent.com/6841787/292511015-600e23f3-9402-4364-8a7f-d00dd259aefa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNzIwNzUsIm5iZiI6MTcwMzI3MTc3NSwicGF0aCI6Ii82ODQxNzg3LzI5MjUxMTAxNS02MDBlMjNmMy05NDAyLTQzNjQtOGE3Zi1kMDBkZDI1OWFlZmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMTkwMjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmFhMmNjNmE0NGJmOGZiMzJmNmI2ODhmNWU5OWNiNjk0YzVlMWZkYzQwNDg5M2Q0ZDY5OTUwYmVhZWRiZTJhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.y4Ar9HQy5HcaWxdPRThKkcx9DWc-t_WI6sVV7IfyaRY) I am still getting this error this morning.



Same Error

**Comment by FreddyCi** [comment]
<img width="565" alt="Screenshot 2023-12-22 at 12 56 11 PM" src="https://github.com/Pythagora-io/gpt-pilot/assets/82235033/01377052-bd7f-4525-9f0a-d70a08130e29">
Having the same issue on M2 Mac

**Comment by Siddharth1988** [comment]
Guys any update ? I also have the same dotenv error as others stated.

**Comment by senko** [comment]
Hi guys,

we're still working on the issue. In the meantime please try the workaround steps from the description, while making sure you're in the right directory.

**Comment by RFARREY** [comment]
![Screenshot 2023-12-23 005124](https://github.com/Pythagora-io/gpt-pilot/assets/45320379/18a2bb82-a521-40b4-ab69-35fa7eb19ca7)


I just don't understand why Youtubers are reviewing this app when it just doesn't work. ffs!

**Comment by Siddharth1988** [comment]
The workaround still lands at the dotenv not found error. Any other workaround other than what is posted above ?

**Comment by coelhomultimedia** [comment]
Solved with this steps:
    Delete the 'gpt-pilot' folder.
    Install another version of the plugin and select 0.0.20.
    Use the plugin until the error occurs.
    Delete the 'gpt-pilot' folder.
    Add the new version 0.0.21.

**Comment by Eforen** [comment]
> ![Screenshot 2023-12-23 005106](https://private-user-images.githubusercontent.com/45320379/292596762-19edc174-64dd-4293-9515-2c684ffefc72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyODY1OTMsIm5iZiI6MTcwMzI4NjI5MywicGF0aCI6Ii80NTMyMDM3OS8yOTI1OTY3NjItMTllZGMxNzQtNjRkZC00MjkzLTk1MTUtMmM2ODRmZmVmYzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDIzMDQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NTY5OWE5ZmIxMzI1ZGMwNTU3YjJmY2FmZDEzYTE5MjMxMTc4MWJkZTk1N2E1OGNkZTMzOWVkNjFhMDgxM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kZcmLtYgXB_sI11Xa6EOy01mhgpAiVfh5ZjPp9gfk7Q)
> 
> I just don't understand why Youtubers are reviewing this app when it just doesn't work. ffs!

because the youtubers use mac computers

**Comment by aaronjolson** [comment]
I got this working on a fresh version of the extension I downloaded yesterday. You might want to try uninstalling + deleting your current extension (and the entire GPT-Pilot folder) and redownloading / starting over if you have been having issues up to this point.

Make sure you have a recent version of Python installed, I am using python 3.10.6

To start, when I opened my terminal in VSCode. I brought me to` C:\Users\aaron\PycharmProjects\GPT_Pilot\gpt-pilot\workspace` This is correct, but notice the `\workspace`.
If you are there, `cd ..` up a level into \gpt-pilot

In the gpt-pilot dir, confirm there is a requirements.txt file in that directory using `dir` or `ls`. Also confirm there is a directory there called \pilot-env
If that directory already exists, run `./pilot-env/Scripts/activate`
if not, run  
```
python -m venv pilot-env
./pilot-env/Scripts/activate
```
install packages with `pip install -r requirements.txt`
go to the pilot subdirectory (not pilot-env, just pilot), then run `python db_init.p`y to initialize the database

Once you have done all of this, reopen the gpt-pilot extension using the icon on the left panel in vs-code. signin and select new project. It should initialize correctly now.

**Comment by MikeTheBard** [comment]
Getting this error with @aaronjolson's steps.

![37Vtgcr](https://github.com/Pythagora-io/gpt-pilot/assets/146694195/237ab1da-75e4-4af7-984a-faa16bb30c84)

**Comment by Bundbary** [comment]
> @Siddharth1988 @FreddyCi @RFARREY
> 
> I got this working on a fresh version of the extension I downloaded yesterday. You might want to try uninstalling + deleting your current extension (and the entire GPT-Pilot folder) and redownloading / starting over if you have been having issues up to this point.
> 
> Make sure you have a recent version of Python installed, I am using python 3.10.6 on Windows 11 Make sure you can run the `python` command from inside your terminal in vscode and the expected version initializes (pretty sure it needs to be greater than version 3.9. I use 3.10.6 because stable diffusion required it)
> 
> To start, when I opened my terminal in VSCode. It brought me to` C:\Users\aaron\PycharmProjects\GPT_Pilot\gpt-pilot\workspace` This is correct, but notice the `\workspace`. If you are there, `cd ..` up a level into \gpt-pilot
> 
> In the gpt-pilot dir, confirm there is a requirements.txt file in that directory using `dir` or `ls`. Also confirm there is a directory there called \pilot-env If that directory already exists, run `./pilot-env/Scripts/activate` if not, run
> 
> ```
> python -m venv pilot-env
> ./pilot-env/Scripts/activate
> ```
> 
> Once the virtual environment is activated, install required packages with `pip install -r requirements.txt` go to the pilot subdirectory (not pilot-env, just pilot), `cd pilot`, then run `python db_init.p` to initialize the database.
> 
> Once you have done all of this, reopen the gpt-pilot extension using the icon on the left panel in vscode. signin, and select new project. It should initialize correctly now.

There's a slight typo here, missing the last character of the last file extension to run. Should be "db_init.py" (that got me working)

**Comment by MikeTheBard** [comment]
> > @Siddharth1988 @FreddyCi @RFARREY
> > I got this working on a fresh version of the extension I downloaded yesterday. You might want to try uninstalling + deleting your current extension (and the entire GPT-Pilot folder) and redownloading / starting over if you have been having issues up to this point.
> > Make sure you have a recent version of Python installed, I am using python 3.10.6 on Windows 11 Make sure you can run the `python` command from inside your terminal in vscode and the expected version initializes (pretty sure it needs to be greater than version 3.9. I use 3.10.6 because stable diffusion required it)
> > To start, when I opened my terminal in VSCode. It brought me to` C:\Users\aaron\PycharmProjects\GPT_Pilot\gpt-pilot\workspace` This is correct, but notice the `\workspace`. If you are there, `cd ..` up a level into \gpt-pilot
> > In the gpt-pilot dir, confirm there is a requirements.txt file in that directory using `dir` or `ls`. Also confirm there is a directory there called \pilot-env If that directory already exists, run `./pilot-env/Scripts/activate` if not, run
> > ```
> > python -m venv pilot-env
> > ./pilot-env/Scripts/activate
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Once the virtual environment is activated, install required packages with `pip install -r requirements.txt` go to the pilot subdirectory (not pilot-env, just pilot), `cd pilot`, then run `python db_init.p` to initialize the database.
> > Once you have done all of this, reopen the gpt-pilot extension using the icon on the left panel in vscode. signin, and select new project. It should initialize correctly now.
> 
> There's a slight typo here, missing the last character of the last file extension to run. Should be "db_init.py" (that got me working)

I followed these instructions and caught the typo, but still end up with my errors above.

**Comment by aaronjolson** [comment]
@MikeTheBard - what version of windows + python are you using?
Did all the dependencies install correctly when you ran `pip install -r requirements.txt` ?

**Comment by aaronjolson** [comment]
> Just adding this to see if it helps locate the cause of this issue. After the install, I get this error: Traceback (most recent call last): File "c:\AI\gpt-pilot\workspace/gpt-pilot/pilot/main.py", line 8, in from dotenv import load_dotenv ModuleNotFoundError: No module named 'dotenv'
> 
> See image
> 
> I did try deleting the workspace directory and letting it re-initialize it. This caused an error because the last slash in the path was incorrect, (see image) which made it just loop. I manually created the directories and it did re-initialize the workspace, but didn't fix the above error.
> 
> Brian
> 
> ![New app error](https://private-user-images.githubusercontent.com/40923847/292536021-616b3df3-e490-4273-8c39-84f37f1ab2d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNjU2MzcsIm5iZiI6MTcwMzM2NTMzNywicGF0aCI6Ii80MDkyMzg0Ny8yOTI1MzYwMjEtNjE2YjNkZjMtZTQ5MC00MjczLThjMzktODRmMzdmMWFiMmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDIxMDIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2OWNjMzBmYzQyZTRhMjYwYWQ4YjgzYzM3NGRhOTFiODkzZTZlY2I4YjY2YTNkNzAxNzUyMDdiNGRjMDQ2N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jwR1MmsicZ-3mz6MazRDRvVEju_lM0Sw-zzlkX_tNKw) ![workspace](https://private-user-images.githubusercontent.com/40923847/292536052-5288b53d-0d97-4bb4-908f-a533ad09dfc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNjU2MzcsIm5iZiI6MTcwMzM2NTMzNywicGF0aCI6Ii80MDkyMzg0Ny8yOTI1MzYwNTItNTI4OGI1M2QtMGQ5Ny00YmI0LTkwOGYtYTUzM2FkMDlkZmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDIxMDIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMGMxZjdjMDUwNTkyMzg0ZDZhNTM3NzkxMmQ5NGYzMTkxYTFkMDBmMDVmMmM0YmY1N2ViZTM2ZWNmYjE4NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._PB0Ny8GJOQV2myZwdpO-O_C02WDspTcsv1mHGcGBM0)

@brain1961 - I can tell from you above you are definitely in the wrong path (wrong directory). You have went and created new directories inside of workspace. You shouldn't be inside of workspace at all. See my instructions https://github.com/Pythagora-io/gpt-pilot/issues/387#issuecomment-1868328940

**Comment by MikeTheBard** [comment]
> @MikeTheBard - what version of windows + python are you using? Did all the dependencies install correctly when you ran `pip install -r requirements.txt` ?

Windows 10 Pro 64-bit (10.0, Build 19045)

Yes, all installed correctly.

**Comment by brain1961** [comment]
@aaronjolson - You are correct. I had installed an earlier cli version of this and I didn't think about it when I installed the extension. I removed that folder and did a clean install and it now works great. My apologies for this and thanks for all your work.

**Comment by fahdmirza** [comment]
Following above workarounds and still doesn't work. This project has still a long way to go to be even in Alpha. Thanks.

**Comment by dreamrec** [comment]
> @Siddharth1988 @FreddyCi @RFARREY I was getting the missing dotenv issue at first.
> 
> I got this working on a fresh version of the extension I downloaded yesterday. You might want to try uninstalling + deleting your current extension (and the entire GPT-Pilot folder) and redownloading / starting over if you have been having issues up to this point.
> 
> Make sure you have a recent version of Python installed, I am using python 3.10.6 on Windows 11 Make sure you can run the `python` command from inside your terminal in vscode and the expected version initializes (pretty sure it needs to be greater than version 3.9. I use 3.10.6 because stable diffusion required it)
> 
> To start, when I opened my terminal in VSCode. It brought me to` C:\Users\aaron\PycharmProjects\GPT_Pilot\gpt-pilot\workspace` This is correct, but notice the `\workspace`. If you are there, `cd ..` up a level into \gpt-pilot
> 
> In the gpt-pilot dir, confirm there is a requirements.txt file in that directory using `dir` or `ls`. Also confirm there is a directory there called \pilot-env If that directory already exists, run `./pilot-env/Scripts/activate` if not, run
> 
> ```
> python -m venv pilot-env
> ./pilot-env/Scripts/activate
> ```
> 
> Once the virtual environment is activated, install required packages with `pip install -r requirements.txt` go to the pilot subdirectory (not pilot-env, just pilot), `cd pilot`, then run `python db_init.py` to initialize the database.
> 
> Once you have done all of this, reopen the gpt-pilot extension using the icon on the left panel in vscode. signin, and select new project. It should initialize correctly now.

![Screenshot 2023-12-24 183819](https://github.com/Pythagora-io/gpt-pilot/assets/11504934/6a2d89ac-927f-4854-96c1-42889d076df3)

error after doing all the steps above .

**Comment by pavel-pythagora** [comment]
We close the tab when gpt-pilot sends print('', type='exit'). I think it is possible to show a message with 'Do you want to close gpt-pilot?' and answers.

**Comment by JS1920** [comment]
> > When setting up GPT-Pilot VSCode extension in windows, one of the steps is to create the Python virtual environment (venv).
> > This can fail (for as of yet unknown reason), and this is what the users see:
> > ![image](https://private-user-images.githubusercontent.com/3362/292340111-7dbd5926-c94b-404c-b1eb-eaaef606c701.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjI2MjUsIm5iZiI6MTcwMzIyMjMyNSwicGF0aCI6Ii8zMzYyLzI5MjM0MDExMS03ZGJkNTkyNi1jOTRiLTQwNGMtYjFlYi1lYWFlZjYwNmM3MDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDUxODQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmY0MWZjNmI5NjcyYzJhY2IwOTQ5NjExNzE4ODE5NmE4MWY0NjczMWVhMzZkM2MxMDgzMWE1YzUyODYzODg4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wlBQvFkwK1BQWIMqvUkWVGSDV0bH3YZ43iXakDLOfhI)
> > Temporary workaround:
> > ```
> > 1. open command line in the `gpt-pilot` sub-directory of the folder which you selected for the installation of GPT Pilot (there should be `requirements.txt` file already there)
> > 
> > 2. create the virtual environment with `python -m venv pilot-env`
> > 
> > 3. activate the environment with `pilot-env\Scripts\activate`
> > 
> > 4. install packages with `pip install -r requirements.txt`
> > 
> > 5. go to the `pilot` subdirectory (not `pilot-env`, just `pilot`), then run `python db_init.py` to initialize the database
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After doing the above steps, the VSCode extension should start working.
> 
> This worked for me

This same workaround works for me as well on Windows 10 machine!

**Comment by e404nothing** [comment]
> > @Siddharth1988 @FreddyCi @RFARREY
> > I got this working on a fresh version of the extension I downloaded yesterday. You might want to try uninstalling + deleting your current extension (and the entire GPT-Pilot folder) and redownloading / starting over if you have been having issues up to this point.
> > Make sure you have a recent version of Python installed, I am using python 3.10.6 on Windows 11 Make sure you can run the `python` command from inside your terminal in vscode and the expected version initializes (pretty sure it needs to be greater than version 3.9. I use 3.10.6 because stable diffusion required it)
> > To start, when I opened my terminal in VSCode. It brought me to` C:\Users\aaron\PycharmProjects\GPT_Pilot\gpt-pilot\workspace` This is correct, but notice the `\workspace`. If you are there, `cd ..` up a level into \gpt-pilot
> > In the gpt-pilot dir, confirm there is a requirements.txt file in that directory using `dir` or `ls`. Also confirm there is a directory there called \pilot-env If that directory already exists, run `./pilot-env/Scripts/activate` if not, run
> > ```
> > python -m venv pilot-env
> > ./pilot-env/Scripts/activate
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Once the virtual environment is activated, install required packages with `pip install -r requirements.txt` go to the pilot subdirectory (not pilot-env, just pilot), `cd pilot`, then run `python db_init.p` to initialize the database.
> > Once you have done all of this, reopen the gpt-pilot extension using the icon on the left panel in vscode. signin, and select new project. It should initialize correctly now.
> 
> There's a slight typo here, missing the last character of the last file extension to run. Should be "db_init.py" (that got me working)

This worked for me with Python 3.12.1

**Comment by Tokyofloripa** [comment]
Same problem, Windows 11
I followed all the suggestions above, nothing solved

Hopefully we get some kind soul to help

Thanks

**Comment by e404nothing** [comment]
> Same problem, Window

> Same problem, Windows 11 I followed all the suggestions above, nothing solved
> 
> Hopefully we get some kind soul to help
> 
> Thanks

Are you on windows 11 with VScode?

**Comment by Tokyofloripa** [comment]
> > Same problem, Window
> 
> > Same problem, Windows 11 I followed all the suggestions above, nothing solved
> > Hopefully we get some kind soul to help
> > Thanks
> 
> Are you on windows 11 with VScode?

Yes, VScode on windows 11.
Error during the "Setup Python Environment" phase.

**Comment by e404nothing** [comment]
> > > Same problem, Window
> > 
> > > Same problem, Windows 11 I followed all the suggestions above, nothing solved
> > > Hopefully we get some kind soul to help
> > > Thanks
> > 
> > Are you on windows 11 with VScode?
> 
> Yes, VScode on windows 11.
> Error during the "Setup Python Environment" phase.

Ok, have you set up the Path in Environmental Variables? Can you post your whole error log file?

**Comment by Tokyofloripa** [comment]
> > > > Same problem, Window
> > > 
> > > 
> > > > Same problem, Windows 11 I followed all the suggestions above, nothing solved
> > > > Hopefully we get some kind soul to help
> > > > Thanks
> > > 
> > > 
> > > Are you on windows 11 with VScode?
> > 
> > 
> > Yes, VScode on windows 11.
> > Error during the "Setup Python Environment" phase.
> 
> Ok, have you set up the Path in Environmental Variables? Can you post your whole error log file?

Error installing GPT Pilot: Command failed: "c:\Users\rafae\Documents"\gpt-pilot\pilot-env\Scripts\python -m pip install -r requirements.txt C:\Users\rafae\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'c:\\gpt-pilot\\pilot-env\\Scripts\\python': [Errno 2] No such file or directory

**Comment by e404nothing** [comment]
> > > > > Same problem, Window
> > > > 
> > > > 
> > > > > Same problem, Windows 11 I followed all the suggestions above, nothing solved
> > > > > Hopefully we get some kind soul to help
> > > > > Thanks
> > > > 
> > > > 
> > > > Are you on windows 11 with VScode?
> > > 
> > > 
> > > Yes, VScode on windows 11.
> > > Error during the "Setup Python Environment" phase.
> > 
> > Ok, have you set up the Path in Environmental Variables? Can you post your whole error log file?
> 
> Error installing GPT Pilot: Command failed: "c:\Users\rafae\Documents"\gpt-pilot\pilot-env\Scripts\python -m pip install -r requirements.txt C:\Users\rafae\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'c:\\gpt-pilot\\pilot-env\\Scripts\\python': [Errno 2] No such file or directory

Yeah, double check that your Path is correctly set up. Do you know how to do that?

**Comment by Tokyofloripa** [comment]
> > > > > > Same problem, Window
> > > > > 
> > > > > 
> > > > > > Same problem, Windows 11 I followed all the suggestions above, nothing solved
> > > > > > Hopefully we get some kind soul to help
> > > > > > Thanks
> > > > > 
> > > > > 
> > > > > Are you on windows 11 with VScode?
> > > > 
> > > > 
> > > > Yes, VScode on windows 11.
> > > > Error during the "Setup Python Environment" phase.
> > > 
> > > 
> > > Ok, have you set up the Path in Environmental Variables? Can you post your whole error log file?
> > 
> > 
> > Error installing GPT Pilot: Command failed: "c:\Users\rafae\Documents"\gpt-pilot\pilot-env\Scripts\python -m pip install -r requirements.txt C:\Users\rafae\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'c:\gpt-pilot\pilot-env\Scripts\python': [Errno 2] No such file or directory
> 
> Yeah, double check that your Path is correctly set up. Do you know how to do that?

Can you point how to do it? I come from C#, just learning Python on the fly.

**Comment by LeonOstrez** [comment]
Hi everyone, we are still trying to find a fix for this issue.

There is new version of extension live. After updating extension you should select new folder in "settings" to get a fresh install of GPT Pilot.

If you are still having this issue, I would be more than happy to jump on a call and help you with debugging and setting up GPT Pilot. Please DM me on discord (leonostrez) and we can hop on a call.

**Comment by SerenityNrrd** [comment]
> Hi everyone, we are still trying to find a fix for this issue.
> 
> There is new version of extension live. After updating extension you should select new folder in "settings" to get a fresh install of GPT Pilot.
> 
> If you are still having this issue, I would be more than happy to jump on a call and help you with debugging and setting up GPT Pilot. Please DM me on discord (leonostrez) and we can hop on a call.

This worked for me .. TY

**Comment by MikeTheBard** [comment]
This update fixed the issue for me. Thanks for your work on this project.

**Comment by rmannby** [comment]
Hi, I have update to latest extension and tried the above and selected a new folder but still got the error:

> Traceback (most recent call last):
> File "d:\Dropbox\Python\TestPilot\gpt-pilot\pilot\main.py", line 8, in
> from dotenv import load_dotenv
> ModuleNotFoundError: No module named 'dotenv'

Regards
Roger

**Comment by aluk123** [comment]
> > @Siddharth1988 @FreddyCi @RFARREY
> > I got this working on a fresh version of the extension I downloaded yesterday. You might want to try uninstalling + deleting your current extension (and the entire GPT-Pilot folder) and redownloading / starting over if you have been having issues up to this point.
> > Make sure you have a recent version of Python installed, I am using python 3.10.6 on Windows 11 Make sure you can run the `python` command from inside your terminal in vscode and the expected version initializes (pretty sure it needs to be greater than version 3.9. I use 3.10.6 because stable diffusion required it)
> > To start, when I opened my terminal in VSCode. It brought me to` C:\Users\aaron\PycharmProjects\GPT_Pilot\gpt-pilot\workspace` This is correct, but notice the `\workspace`. If you are there, `cd ..` up a level into \gpt-pilot
> > In the gpt-pilot dir, confirm there is a requirements.txt file in that directory using `dir` or `ls`. Also confirm there is a directory there called \pilot-env If that directory already exists, run `./pilot-env/Scripts/activate` if not, run
> > ```
> > python -m venv pilot-env
> > ./pilot-env/Scripts/activate
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Once the virtual environment is activated, install required packages with `pip install -r requirements.txt` go to the pilot subdirectory (not pilot-env, just pilot), `cd pilot`, then run `python db_init.p` to initialize the database.
> > Once you have done all of this, reopen the gpt-pilot extension using the icon on the left panel in vscode. signin, and select new project. It should initialize correctly now.
> 
> There's a slight typo here, missing the last character of the last file extension to run. Should be "db_init.py" (that got me working)

Works for me thanks and HNY.

**Comment by Adamchanadam** [comment]
> @Siddharth1988 @FreddyCi @RFARREY I was getting the missing dotenv issue at first.
> 
> I got this working on a fresh version of the extension I downloaded yesterday. You might want to try uninstalling + deleting your current extension (and the entire GPT-Pilot folder) and redownloading / starting over if you have been having issues up to this point.
> 
> Make sure you have a recent version of Python installed, I am using python 3.10.6 on Windows 11 Make sure you can run the `python` command from inside your terminal in vscode and the expected version initializes (pretty sure it needs to be greater than version 3.9. I use 3.10.6 because stable diffusion required it)
> 
> To start, when I opened my terminal in VSCode. It brought me to` C:\Users\aaron\PycharmProjects\GPT_Pilot\gpt-pilot\workspace` This is correct, but notice the `\workspace`. If you are there, `cd ..` up a level into \gpt-pilot
> 
> In the gpt-pilot dir, confirm there is a requirements.txt file in that directory using `dir` or `ls`. Also confirm there is a directory there called \pilot-env If that directory already exists, run `./pilot-env/Scripts/activate` if not, run
> 
> ```
> python -m venv pilot-env
> ./pilot-env/Scripts/activate
> ```
> 
> Once the virtual environment is activated, install required packages with `pip install -r requirements.txt` go to the pilot subdirectory (not pilot-env, just pilot), `cd pilot`, then run `python db_init.py` to initialize the database.
> 
> Once you have done all of this, reopen the gpt-pilot extension using the icon on the left panel in vscode. signin, and select new project. It should initialize correctly now.

Thanks , it works for me under Windows 11

**Comment by Blank0120** [comment]
How to set up python environment under windows 10? I can not switch python env after I initialized even if I reinstall Vscode extension and delete .gpt-pilot in my profile.And I select new folder in "settings" to get a fresh install of GPT Pilot. Then when I click "Setup python environment" in vscode, it just reopen and does not happend anything about python environment.

> Hi everyone, we are still trying to find a fix for this issue.
> 
> There is new version of extension live. After updating extension you should select new folder in "settings" to get a fresh install of GPT Pilot. If this worked for you please give it a thumbs up or leave a comment so we know.
> 
> If you are still having this issue, I would be more than happy to jump on a call and help you with debugging and setting up GPT Pilot. Please DM me on discord (leonostrez) and we can hop on a call.
